version: "3.7"
services:
  gra:
    image: grafana/grafana
    environment:
      - GF_INSTALL_PLUGINGS="Geomap,grafana-worldmap-panel"
    volumes:
      #      - ./datasources:/etc/grafana/provisioning/datasources/
      - ./grafana_dashboards:/etc/grafana/provisioning/dashboards/
        #- ./grafana_data/:/var/lib/grafana:rw
    ports:
        - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql
    volumes:
      - covid_dashboard_db:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  covid_dashboard_db:
  covid_dashboard_gra:
